version: '3'
services:
  app:
    image: quay.io/continuouspipe/php7.2-nginx:latest
    environment:
      XDEBUG_REMOTE_ENABLED: 'true'
      XDEBUG_REMOTE_HOST: 'host.docker.internal'
      XDEBUG_REMOTE_PORT: '9000'
      XDEBUG_REMOTE_AUTOSTART: 'true'
      PHP_IDE_CONFIG: 'serverName=github-tool-docker'
    env_file:
      - app.env
    working_dir: /app
    volumes:
      - .:/app
